-- vim: set ft=sql:
-- ============================================================
-- 02_clean_mysql.sql
-- Silver Layer: loans_staging → loans_clean
-- ============================================================
USE lending_club;

-- ============================================================
-- BLOQUE 1: Crear tabla Silver con tipos correctos
-- ============================================================
DROP TABLE IF EXISTS loans_clean;

CREATE TABLE loans_clean (
    id                      VARCHAR(20),
    member_id               VARCHAR(20),
    loan_amnt               DECIMAL(12,2),
    funded_amnt             DECIMAL(12,2),
    funded_amnt_inv         DECIMAL(12,2),
    term                    TINYINT,
    int_rate                DECIMAL(7,2),
    installment             DECIMAL(10,2),
    grade                   CHAR(1),
    sub_grade               VARCHAR(3),
    emp_title               VARCHAR(100),
    emp_length              VARCHAR(15),
    home_ownership          VARCHAR(20),
    annual_inc              DECIMAL(14,2),
    verification_status     VARCHAR(30),
    issue_d                 DATE,
    loan_status             VARCHAR(100),
    pymnt_plan              VARCHAR(5),
    purpose                 VARCHAR(30),
    title                   VARCHAR(100),
    zip_code                VARCHAR(10),
    addr_state              VARCHAR(5),
    dti                     DECIMAL(8,2),
    delinq_2yrs             INT,
    earliest_cr_line        DATE,
    fico_range_low          INT,
    fico_range_high         INT,
    inq_last_6mths          INT,
    mths_since_last_delinq  INT,
    mths_since_last_record  INT,
    open_acc                INT,
    pub_rec                 INT,
    revol_bal               DECIMAL(14,2),
    revol_util              DECIMAL(7,2),
    total_acc               INT,
    initial_list_status     CHAR(1),
    out_prncp               DECIMAL(12,2),
    out_prncp_inv           DECIMAL(12,2),
    total_pymnt             DECIMAL(14,2),
    total_pymnt_inv         DECIMAL(14,2),
    total_rec_prncp         DECIMAL(14,2),
    total_rec_int           DECIMAL(14,2),
    total_rec_late_fee      DECIMAL(10,2),
    recoveries              DECIMAL(12,2),
    collection_recovery_fee DECIMAL(12,2),
    last_pymnt_d            DATE,
    last_pymnt_amnt         DECIMAL(12,2),
    next_pymnt_d            DATE,
    last_credit_pull_d      DATE,
    last_fico_range_high    INT,
    last_fico_range_low     INT,
    collections_12_mths_ex_med      INT,
    mths_since_last_major_derog     INT,
    policy_code                     TINYINT,
    application_type                VARCHAR(20),
    annual_inc_joint                DECIMAL(14,2),
    dti_joint                       DECIMAL(8,2),
    verification_status_joint       VARCHAR(30),
    acc_now_delinq                  INT,
    tot_coll_amt                    DECIMAL(14,2),
    tot_cur_bal                     DECIMAL(14,2),
    open_acc_6m                     INT,
    open_act_il                     INT,
    open_il_12m                     INT,
    open_il_24m                     INT,
    mths_since_rcnt_il              INT,
    total_bal_il                    DECIMAL(14,2),
    il_util                         DECIMAL(7,2),
    open_rv_12m                     INT,
    open_rv_24m                     INT,
    max_bal_bc                      DECIMAL(12,2),
    all_util                        DECIMAL(7,2),
    total_rev_hi_lim                DECIMAL(14,2),
    inq_fi                          INT,
    total_cu_tl                     INT,
    inq_last_12m                    INT,
    acc_open_past_24mths            INT,
    avg_cur_bal                     DECIMAL(12,2),
    bc_open_to_buy                  DECIMAL(12,2),
    bc_util                         DECIMAL(7,2),
    chargeoff_within_12_mths        INT,
    delinq_amnt                     DECIMAL(12,2),
    mo_sin_old_il_acct              INT,
    mo_sin_old_rev_tl_op            INT,
    mo_sin_rcnt_rev_tl_op           INT,
    mo_sin_rcnt_tl                  INT,
    mort_acc                        INT,
    mths_since_recent_bc            INT,
    mths_since_recent_bc_dlq        INT,
    mths_since_recent_inq           INT,
    mths_since_recent_revol_delinq  INT,
    num_accts_ever_120_pd           INT,
    num_actv_bc_tl                  INT,
    num_actv_rev_tl                 INT,
    num_bc_sats                     INT,
    num_bc_tl                       INT,
    num_il_tl                       INT,
    num_op_rev_tl                   INT,
    num_rev_accts                   INT,
    num_rev_tl_bal_gt_0             INT,
    num_sats                        INT,
    num_tl_120dpd_2m                INT,
    num_tl_30dpd                    INT,
    num_tl_90g_dpd_24m              INT,
    num_tl_op_past_12m              INT,
    pct_tl_nvr_dlq                  DECIMAL(7,2),
    percent_bc_gt_75                DECIMAL(7,2),
    pub_rec_bankruptcies            INT,
    tax_liens                       INT,
    tot_hi_cred_lim                 DECIMAL(14,2),
    total_bal_ex_mort               DECIMAL(14,2),
    total_bc_limit                  DECIMAL(12,2),
    total_il_high_credit_limit      DECIMAL(14,2),
    revol_bal_joint                         DECIMAL(14,2),
    sec_app_fico_range_low                  INT,
    sec_app_fico_range_high                 INT,
    sec_app_earliest_cr_line                DATE,
    sec_app_inq_last_6mths                  INT,
    sec_app_mort_acc                        INT,
    sec_app_open_acc                        INT,
    sec_app_revol_util                      DECIMAL(7,2),
    sec_app_open_act_il                     INT,
    sec_app_num_rev_accts                   INT,
    sec_app_chargeoff_within_12_mths        INT,
    sec_app_collections_12_mths_ex_med      INT,
    sec_app_mths_since_last_major_derog     INT,
    hardship_flag               VARCHAR(5),
    hardship_type               VARCHAR(50),
    hardship_reason             VARCHAR(50),
    hardship_status             VARCHAR(20),
    deferral_term               INT,
    hardship_amount             DECIMAL(12,2),
    hardship_start_date         DATE,
    hardship_end_date           DATE,
    payment_plan_start_date     DATE,
    hardship_length             INT,
    hardship_dpd                INT,
    hardship_loan_status        VARCHAR(100),
    orig_projected_additional_accrued_interest DECIMAL(12,2),
    hardship_payoff_balance_amount  DECIMAL(12,2),
    hardship_last_payment_amount    DECIMAL(12,2),
    disbursement_method         VARCHAR(20),
    debt_settlement_flag        VARCHAR(5),
    debt_settlement_flag_date   DATE,
    settlement_status           VARCHAR(20),
    settlement_date             DATE,
    settlement_amount           DECIMAL(12,2),
    settlement_percentage       DECIMAL(7,2),
    settlement_term             INT
);

-- ============================================================
-- BLOQUE 2: INSERT con casteos correctos
-- ============================================================
INSERT INTO loans_clean
SELECT
    NULLIF(id, ''),
    NULLIF(member_id, ''),
    NULLIF(loan_amnt, ''),
    NULLIF(funded_amnt, ''),
    NULLIF(funded_amnt_inv, ''),
    NULLIF(TRIM(REGEXP_REPLACE(term, '[^0-9]', '')), ''),
    NULLIF(int_rate, ''),
    NULLIF(installment, ''),
    NULLIF(grade, ''),
    NULLIF(sub_grade, ''),
    NULLIF(emp_title, ''),
    NULLIF(emp_length, ''),
    NULLIF(home_ownership, ''),
    NULLIF(annual_inc, ''),
    NULLIF(verification_status, ''),
    CASE WHEN issue_d                   = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', issue_d),                   '%d-%b-%Y') END,
    NULLIF(loan_status, ''),
    NULLIF(pymnt_plan, ''),
    NULLIF(purpose, ''),
    NULLIF(title, ''),
    NULLIF(zip_code, ''),
    NULLIF(addr_state, ''),
    NULLIF(dti, ''),
    NULLIF(delinq_2yrs, ''),
    CASE WHEN earliest_cr_line          = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', earliest_cr_line),          '%d-%b-%Y') END,
    NULLIF(fico_range_low, ''),
    NULLIF(fico_range_high, ''),
    NULLIF(inq_last_6mths, ''),
    NULLIF(mths_since_last_delinq, ''),
    NULLIF(mths_since_last_record, ''),
    NULLIF(open_acc, ''),
    NULLIF(pub_rec, ''),
    NULLIF(revol_bal, ''),
    NULLIF(revol_util, ''),
    NULLIF(total_acc, ''),
    NULLIF(initial_list_status, ''),
    NULLIF(out_prncp, ''),
    NULLIF(out_prncp_inv, ''),
    NULLIF(total_pymnt, ''),
    NULLIF(total_pymnt_inv, ''),
    NULLIF(total_rec_prncp, ''),
    NULLIF(total_rec_int, ''),
    NULLIF(total_rec_late_fee, ''),
    NULLIF(recoveries, ''),
    NULLIF(collection_recovery_fee, ''),
    CASE WHEN last_pymnt_d              = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', last_pymnt_d),              '%d-%b-%Y') END,
    NULLIF(last_pymnt_amnt, ''),
    CASE WHEN next_pymnt_d              = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', next_pymnt_d),              '%d-%b-%Y') END,
    CASE WHEN last_credit_pull_d        = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', last_credit_pull_d),        '%d-%b-%Y') END,
    NULLIF(last_fico_range_high, ''),
    NULLIF(last_fico_range_low, ''),
    NULLIF(collections_12_mths_ex_med, ''),
    NULLIF(mths_since_last_major_derog, ''),
    NULLIF(policy_code, ''),
    NULLIF(application_type, ''),
    NULLIF(annual_inc_joint, ''),
    NULLIF(dti_joint, ''),
    NULLIF(verification_status_joint, ''),
    NULLIF(acc_now_delinq, ''),
    NULLIF(tot_coll_amt, ''),
    NULLIF(tot_cur_bal, ''),
    NULLIF(open_acc_6m, ''),
    NULLIF(open_act_il, ''),
    NULLIF(open_il_12m, ''),
    NULLIF(open_il_24m, ''),
    NULLIF(mths_since_rcnt_il, ''),
    NULLIF(total_bal_il, ''),
    NULLIF(il_util, ''),
    NULLIF(open_rv_12m, ''),
    NULLIF(open_rv_24m, ''),
    NULLIF(max_bal_bc, ''),
    NULLIF(all_util, ''),
    NULLIF(total_rev_hi_lim, ''),
    NULLIF(inq_fi, ''),
    NULLIF(total_cu_tl, ''),
    NULLIF(inq_last_12m, ''),
    NULLIF(acc_open_past_24mths, ''),
    NULLIF(avg_cur_bal, ''),
    NULLIF(bc_open_to_buy, ''),
    NULLIF(bc_util, ''),
    NULLIF(chargeoff_within_12_mths, ''),
    NULLIF(delinq_amnt, ''),
    NULLIF(mo_sin_old_il_acct, ''),
    NULLIF(mo_sin_old_rev_tl_op, ''),
    NULLIF(mo_sin_rcnt_rev_tl_op, ''),
    NULLIF(mo_sin_rcnt_tl, ''),
    NULLIF(mort_acc, ''),
    NULLIF(mths_since_recent_bc, ''),
    NULLIF(mths_since_recent_bc_dlq, ''),
    NULLIF(mths_since_recent_inq, ''),
    NULLIF(mths_since_recent_revol_delinq, ''),
    NULLIF(num_accts_ever_120_pd, ''),
    NULLIF(num_actv_bc_tl, ''),
    NULLIF(num_actv_rev_tl, ''),
    NULLIF(num_bc_sats, ''),
    NULLIF(num_bc_tl, ''),
    NULLIF(num_il_tl, ''),
    NULLIF(num_op_rev_tl, ''),
    NULLIF(num_rev_accts, ''),
    NULLIF(num_rev_tl_bal_gt_0, ''),
    NULLIF(num_sats, ''),
    NULLIF(num_tl_120dpd_2m, ''),
    NULLIF(num_tl_30dpd, ''),
    NULLIF(num_tl_90g_dpd_24m, ''),
    NULLIF(num_tl_op_past_12m, ''),
    NULLIF(pct_tl_nvr_dlq, ''),
    NULLIF(percent_bc_gt_75, ''),
    NULLIF(pub_rec_bankruptcies, ''),
    NULLIF(tax_liens, ''),
    NULLIF(tot_hi_cred_lim, ''),
    NULLIF(total_bal_ex_mort, ''),
    NULLIF(total_bc_limit, ''),
    NULLIF(total_il_high_credit_limit, ''),
    NULLIF(revol_bal_joint, ''),
    NULLIF(sec_app_fico_range_low, ''),
    NULLIF(sec_app_fico_range_high, ''),
    CASE WHEN sec_app_earliest_cr_line  = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', sec_app_earliest_cr_line),  '%d-%b-%Y') END,
    NULLIF(sec_app_inq_last_6mths, ''),
    NULLIF(sec_app_mort_acc, ''),
    NULLIF(sec_app_open_acc, ''),
    NULLIF(sec_app_revol_util, ''),
    NULLIF(sec_app_open_act_il, ''),
    NULLIF(sec_app_num_rev_accts, ''),
    NULLIF(sec_app_chargeoff_within_12_mths, ''),
    NULLIF(sec_app_collections_12_mths_ex_med, ''),
    NULLIF(sec_app_mths_since_last_major_derog, ''),
    NULLIF(hardship_flag, ''),
    NULLIF(hardship_type, ''),
    NULLIF(hardship_reason, ''),
    NULLIF(hardship_status, ''),
    NULLIF(deferral_term, ''),
    NULLIF(hardship_amount, ''),
    CASE WHEN hardship_start_date       = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', hardship_start_date),       '%d-%b-%Y') END,
    CASE WHEN hardship_end_date         = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', hardship_end_date),         '%d-%b-%Y') END,
    CASE WHEN payment_plan_start_date   = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', payment_plan_start_date),   '%d-%b-%Y') END,
    NULLIF(hardship_length, ''),
    NULLIF(hardship_dpd, ''),
    NULLIF(hardship_loan_status, ''),
    NULLIF(orig_projected_additional_accrued_interest, ''),
    NULLIF(hardship_payoff_balance_amount, ''),
    NULLIF(hardship_last_payment_amount, ''),
    NULLIF(disbursement_method, ''),
    NULLIF(debt_settlement_flag, ''),
    CASE WHEN debt_settlement_flag_date = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', debt_settlement_flag_date), '%d-%b-%Y') END,
    NULLIF(settlement_status, ''),
    CASE WHEN settlement_date           = '' THEN NULL ELSE STR_TO_DATE(CONCAT('01-', settlement_date),           '%d-%b-%Y') END,
    NULLIF(settlement_amount, ''),
    NULLIF(settlement_percentage, ''),
    NULLIF(settlement_term, '')

FROM loans_staging
WHERE loan_amnt != '';

-- ============================================================
-- BLOQUE 3: Verificación post-inserción
-- ============================================================
SELECT COUNT(*) AS total_filas_clean FROM loans_clean;

SELECT
    MIN(issue_d)     AS fecha_min,
    MAX(issue_d)     AS fecha_max,
    MIN(int_rate)    AS tasa_min,
    MAX(int_rate)    AS tasa_max,
    MIN(loan_amnt)   AS monto_min,
    MAX(loan_amnt)   AS monto_max
FROM loans_clean;
